import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

export const app = express();
const PORT = Number(process.env.PORT) || 3000;

app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ extended: true, limit: "50mb" }));

// Lazy initialize Gemini client
let aiClient: GoogleGenAI | null = null;
function getAI(): GoogleGenAI | null {
  if (!aiClient && process.env.GEMINI_API_KEY) {
    try {
      aiClient = new GoogleGenAI({
        apiKey: process.env.GEMINI_API_KEY,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build",
          },
        },
      });
    } catch (err) {
      console.warn("Failed to initialize GoogleGenAI client:", err);
    }
  }
  return aiClient;
}

// Health check
app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "SYRA NOVA AI Cyber Core",
    version: "1.0.0",
    aiAvailable: !!process.env.GEMINI_API_KEY,
    timestamp: new Date().toISOString(),
  });
});

// 1. AI Text & Message Detector Endpoint (Perplexity, Burstiness, Stylistic Patterns)
app.post("/api/analyze/message", async (req, res) => {
  const { message, messageType = "text" } = req.body;
  if (!message || typeof message !== "string") {
    return res.status(400).json({ error: "Message text is required." });
  }

  const trimmed = message.trim();

  const ai = getAI();
  if (ai) {
    const modelsToTry = ["gemini-3.7-flash", "gemini-3.6-flash"];
    for (const modelName of modelsToTry) {
      try {
        const prompt = `You are an expert AI-detection analyzer. Your task is to evaluate a given message and determine whether it was written by a human or generated by an AI model.

Analyze the input text based on the following metrics:

Perplexity: Evaluate vocabulary predictability. High perplexity indicates human writing; low perplexity suggests AI generation.

Burstiness: Examine sentence length and structural variety. High variance indicates human writing; uniform sentence structures suggest AI generation.

Stylistic Patterns: Check for common AI indicators (e.g., overused transitions, rigid paragraph structures, tonal monotony) vs. human traits (e.g., typos, slang, irregular pacing).

Input Text:
"""
${trimmed.slice(0, 5000)}
"""

Output Format:
Provide your response strictly in the following JSON format:

{
  "verdict": "AI-Generated" | "Human-Written" | "Mixed / Uncertain",
  "confidence_score": 85,
  "perplexity_assessment": "High" | "Medium" | "Low",
  "burstiness_assessment": "High" | "Medium" | "Low",
  "reasoning": {
    "summary": "Detailed overall explanation...",
    "perplexity_reason": "Specific word choice & predictability explanation...",
    "burstiness_reason": "Specific sentence length, rhythm & structure explanation...",
    "key_indicators": ["First specific trait/snippet", "Second specific trait/snippet"]
  }
}`;

        const response = await ai.models.generateContent({
          model: modelName,
          contents: prompt,
          config: {
            responseMimeType: "application/json",
          },
        });

        let text = response.text || "{}";
        text = text.replace(/```json/gi, "").replace(/```/g, "").trim();
        const parsed = JSON.parse(text);

        if (parsed.verdict && typeof parsed.confidence_score === "number" && parsed.reasoning) {
          return res.json({
            verdict: parsed.verdict,
            confidence_score: parsed.confidence_score,
            perplexity_assessment: parsed.perplexity_assessment || "Medium",
            burstiness_assessment: parsed.burstiness_assessment || "Medium",
            reasoning: {
              summary: parsed.reasoning.summary || "AI analysis completed.",
              perplexity_reason: parsed.reasoning.perplexity_reason || "Analyzed vocabulary distribution.",
              burstiness_reason: parsed.reasoning.burstiness_reason || "Analyzed structural rhythm.",
              key_indicators: Array.isArray(parsed.reasoning.key_indicators) ? parsed.reasoning.key_indicators : [],
            },
            // Compatibility fields
            riskScore: parsed.verdict === "AI-Generated" ? parsed.confidence_score : parsed.verdict === "Human-Written" ? 100 - parsed.confidence_score : 50,
            category: parsed.verdict === "AI-Generated" ? "Synthetic AI Text" : parsed.verdict === "Human-Written" ? "Organic Human Text" : "Hybrid / Mixed Content",
            confidence: parsed.confidence_score,
            threatIndicators: Array.isArray(parsed.reasoning.key_indicators) ? parsed.reasoning.key_indicators : [],
            explanation: parsed.reasoning.summary || "",
            recommendations: parsed.verdict === "AI-Generated"
              ? ["Verify authenticity with author", "Check for formulaic AI transitions or hallucinations", "Review factual accuracy of claims"]
              : ["Text demonstrates organic human variance", "Contains natural linguistic pacing", "No synthetic model artifacts detected"]
          });
        }
      } catch (aiErr) {
        console.warn(`Gemini AI message analysis error on ${modelName}:`, aiErr);
      }
    }
  }

  // High-precision Server-side Linguistic Fallback Engine
  const words = trimmed.split(/\s+/).filter(Boolean);
  const rawSentences = trimmed.split(/[.!?]+/).map((s) => s.trim()).filter(Boolean);
  const sentences = rawSentences.length > 0 ? rawSentences : [trimmed];

  // Sentence length variance calculation (Burstiness)
  const sentenceLengths = sentences.map((s) => s.split(/\s+/).filter(Boolean).length);
  const avgLen = sentenceLengths.reduce((a, b) => a + b, 0) / (sentenceLengths.length || 1);
  const variance = sentenceLengths.reduce((sum, len) => sum + Math.pow(len - avgLen, 2), 0) / (sentenceLengths.length || 1);
  const stdDev = Math.sqrt(variance);

  // Perplexity & AI Cliché check
  const lower = trimmed.toLowerCase();
  const aiTransitions = [
    "furthermore", "moreover", "in conclusion", "it is important to note",
    "delve into", "testament to", "beacon of", "tapestry", "multifaceted",
    "paramount", "in summary", "pivotal role", "realm of", "game-changer",
    "holistic approach", "revolutionize", "at its core", "notably"
  ];
  const matchedAiTransitions = aiTransitions.filter((t) => lower.includes(t));

  const humanSlangAndCasual = [
    "lol", "lmao", "btw", "idk", "tbh", "ngl", "bruh", "bro", "dude", "hey",
    "hi", "heyy", "thanks", "thx", "cool", "yeah", "nah", "gonna", "wanna",
    "gotta", "imma", "omg", "kinda", "sorta", "haha", "hahaha"
  ];
  const matchedHumanMarkers = humanSlangAndCasual.filter((h) => {
    const regex = new RegExp(`\\b${h}\\b`, "i");
    return regex.test(lower);
  });

  // Unique word ratio (Lexical diversity)
  const uniqueWords = new Set(words.map((w) => w.toLowerCase()));
  const lexicalDiversity = words.length > 0 ? uniqueWords.size / words.length : 1;

  let isAI = false;
  let isHuman = false;
  let confidence = 85;
  let perplexityAssessment: "High" | "Medium" | "Low" = "Medium";
  let burstinessAssessment: "High" | "Medium" | "Low" = "Medium";
  const keyIndicators: string[] = [];

  // Evaluate Burstiness
  if (stdDev >= 6.5 || (sentenceLengths.length >= 2 && Math.max(...sentenceLengths) - Math.min(...sentenceLengths) >= 12)) {
    burstinessAssessment = "High";
    keyIndicators.push(`High sentence length variance (StdDev: ${stdDev.toFixed(1)} words, ranging from ${Math.min(...sentenceLengths)} to ${Math.max(...sentenceLengths)} words)`);
  } else if (stdDev <= 2.5 && sentences.length >= 2) {
    burstinessAssessment = "Low";
    keyIndicators.push(`Uniform, robotic sentence lengths (StdDev: ${stdDev.toFixed(1)} words) characteristic of AI models`);
  } else {
    burstinessAssessment = "Medium";
  }

  // Evaluate Perplexity & Stylistic
  if (matchedAiTransitions.length >= 2 || (matchedAiTransitions.length >= 1 && burstinessAssessment === "Low")) {
    perplexityAssessment = "Low";
    matchedAiTransitions.forEach((t) => keyIndicators.push(`Stereotypical AI transition phrase: "${t}"`));
  } else if (matchedHumanMarkers.length >= 1 || words.length < 8 || stdDev > 5) {
    perplexityAssessment = "High";
    matchedHumanMarkers.forEach((m) => keyIndicators.push(`Casual human vernacular / slang: "${m}"`));
  } else {
    perplexityAssessment = lexicalDiversity > 0.75 ? "High" : "Medium";
  }

  // Typo and informal punctuation checks
  if (/[!?]{2,}/.test(trimmed) || /\b(im|dont|cant|wont|didnt|youre|theyre)\b/.test(lower)) {
    keyIndicators.push("Informal punctuation / omitted apostrophes typical of rapid human texting");
    perplexityAssessment = "High";
  }

  // Verdict computation
  if (matchedAiTransitions.length >= 2 || (burstinessAssessment === "Low" && perplexityAssessment === "Low")) {
    isAI = true;
    confidence = Math.min(82 + matchedAiTransitions.length * 5, 96);
  } else if (matchedHumanMarkers.length > 0 || burstinessAssessment === "High" || perplexityAssessment === "High") {
    isHuman = true;
    confidence = Math.min(84 + matchedHumanMarkers.length * 4 + (burstinessAssessment === "High" ? 6 : 0), 98);
  } else {
    confidence = 65;
  }

  const verdict: "AI-Generated" | "Human-Written" | "Mixed / Uncertain" = isAI
    ? "AI-Generated"
    : isHuman
    ? "Human-Written"
    : "Mixed / Uncertain";

  const summary =
    verdict === "AI-Generated"
      ? `This text shows clear markers of synthetic AI generation, including low sentence burstiness (${stdDev.toFixed(1)} std dev) and formulaic transition phrases (${matchedAiTransitions.join(", ")}).`
      : verdict === "Human-Written"
      ? `This text demonstrates organic human writing patterns characterized by high linguistic perplexity, natural rhythmic variance, and spontaneous conversational pacing.`
      : `The text displays a blend of predictable syntax and organic variation, indicating either light AI rewriting or edited human prose.`;

  const perplexityReason =
    perplexityAssessment === "High"
      ? "High vocabulary entropy and conversational word choices demonstrate unpredictable, organic human phrasing."
      : perplexityAssessment === "Low"
      ? "Low perplexity detected. Vocabulary choices and transition sequences closely mirror standard LLM training token distributions."
      : "Moderate vocabulary predictability consistent with standard formal writing.";

  const burstinessReason =
    burstinessAssessment === "High"
      ? `High burstiness: Sentence lengths oscillate significantly (ranging from ${Math.min(...sentenceLengths)} to ${Math.max(...sentenceLengths)} words), reflecting human breath and rhythm.`
      : burstinessAssessment === "Low"
      ? `Low burstiness: Sentences maintain a uniform, measured length (average ~${avgLen.toFixed(1)} words), a classic artifact of transformer autoregressive generation.`
      : `Moderate sentence length variance across ${sentences.length} sentence segment(s).`;

  return res.json({
    verdict,
    confidence_score: confidence,
    perplexity_assessment: perplexityAssessment,
    burstiness_assessment: burstinessAssessment,
    reasoning: {
      summary,
      perplexity_reason: perplexityReason,
      burstiness_reason: burstinessReason,
      key_indicators: keyIndicators.length > 0 ? keyIndicators : ["Standard natural syntax flow"],
    },
    // Compatibility fields
    riskScore: verdict === "AI-Generated" ? confidence : verdict === "Human-Written" ? 100 - confidence : 50,
    category: verdict === "AI-Generated" ? "Synthetic AI Text" : verdict === "Human-Written" ? "Organic Human Text" : "Hybrid / Mixed Content",
    confidence: confidence,
    threatIndicators: keyIndicators,
    explanation: summary,
    recommendations: verdict === "AI-Generated"
      ? ["Verify author credentials and factuality", "Check for automated AI hallucinations", "Examine contextual nuance"]
      : ["Natural organic authorship confirmed", "Human linguistic markers present", "No synthetic model hallmarks detected"]
  });
});

// 2. Fake Profile Detector Endpoint
app.post("/api/analyze/profile", async (req, res) => {
  const { url, username, platform = "Instagram", details = "", attributes = {} } = req.body;
  const target = (username || url || "Unknown Profile").trim();
  const cleanDetails = (details || "").trim();

  // Format full forensic survey details for the AI
  const surveyItems: string[] = [];
  if (attributes.accountAge) surveyItems.push(`Account Age: ${attributes.accountAge}`);
  if (attributes.profilePicType) surveyItems.push(`Profile Picture: ${attributes.profilePicType}`);
  if (attributes.postCount) surveyItems.push(`Post History: ${attributes.postCount}`);
  if (attributes.followers) surveyItems.push(`Followers: ${attributes.followers}`);
  if (attributes.following) surveyItems.push(`Following: ${attributes.following}`);
  if (attributes.linkType) surveyItems.push(`Bio External Links: ${attributes.linkType}`);
  if (attributes.unsolicitedDm) surveyItems.push(`Unsolicited Outreach: YES (Sent cold DM)`);
  if (attributes.askingMoneyOrCrypto) surveyItems.push(`Direct Financial Request: YES (Asked for Money/Crypto/UPI/Card/OTP)`);
  if (attributes.promisingPrizeOrJob) surveyItems.push(`Prize/Job Lure: YES (Promised Lottery/Prize/High Returns)`);
  if (attributes.offPlatformRedirection) surveyItems.push(`Off-Platform Redirection: YES (Urged to move to Telegram/WhatsApp)`);
  if (attributes.hasBlueBadge) surveyItems.push(`Official Platform Verification Badge: Present`);
  if (attributes.hasMutualConnections) surveyItems.push(`Known Mutual Connections: Present`);

  const fullContext = [cleanDetails, surveyItems.join(" | ")].filter(Boolean).join("\nDetailed Profile Forensic Questionnaire:\n");
  const combined = `${target} ${fullContext}`.toLowerCase();

  const ai = getAI();
  if (ai) {
    const modelsToTry = ["gemini-3.7-flash", "gemini-3.6-flash"];
    for (const modelName of modelsToTry) {
      try {
        const prompt = `You are SYRA NOVA AI, an expert social media threat analyst and forensic fake profile detector.
Analyze this social account profile accurately:
Platform: ${platform}
Target Handle/URL: ${target}
Profile Bio / Stats / Description / Forensic Questionnaire Data:
${fullContext}

ANALYSIS CRITERIA:
1. "Fake Profile Detected" (authenticityScore: 5 to 35):
   - Asking for money, crypto, gift cards, investment, or OTP in DMs.
   - Promising fake lottery prizes, work-from-home tasks, or iPhone giveaways.
   - Impersonation of brands/celebrities/banks/customer support (e.g. adding _support, _official, _help, _24x7, _care, _airdrop, _claims to brand names).
   - Crypto / Forex / Binary investment solicitations, signals, mining pools, telegram links (t.me/, wa.me/).
   - Romance catfishing (military doctor/surgeon in Syria/deployment, asking for gift cards or off-platform WhatsApp).
   - Fake customer care desks offering refund helplines or toll-free numbers.
   - Bot follower swarms (e.g. following 4,000+ with 10 followers, 0 posts, newly created account).

2. "Suspicious" (authenticityScore: 40 to 68):
   - Unverified promotional accounts, heavy affiliate link shorteners (bit.ly, tinyurl), recent account with high following, unverified fan accounts.

3. "Genuine" (authenticityScore: 75 to 98):
   - Standard organic personal accounts, legitimate creators, authentic verified brand profiles without scam triggers or financial solicitations.

CRITICAL: Weigh all provided forensic questionnaire responses (especially DM solicitation, account age, profile photo, and follower ratios).

Respond strictly in JSON format matching this schema:
{
  "authenticityScore": number (0 to 100),
  "verdict": "Genuine" | "Suspicious" | "Fake Profile Detected",
  "confidence": number (e.g. 92),
  "riskIndicators": string[],
  "explanation": string,
  "recommendations": string[]
}`;

        const response = await ai.models.generateContent({
          model: modelName,
          contents: prompt,
          config: {
            responseMimeType: "application/json",
          },
        });

        let text = response.text || "{}";
        text = text.replace(/```json/gi, "").replace(/```/g, "").trim();
        const parsed = JSON.parse(text);

        if (typeof parsed.authenticityScore === "number" && parsed.verdict) {
          return res.json(parsed);
        }
      } catch (err) {
        console.warn(`Gemini profile analysis failed with model ${modelName}:`, err);
      }
    }
  }

  // Robust Server-side Heuristic Engine
  const flags: string[] = [];
  let deduction = 0;
  let category = "Profile Audit";

  const brandKeywords = [
    "support", "helpdesk", "customercare", "helpline", "official", "care", "service",
    "apple", "google", "meta", "instagram", "facebook", "twitter", "x", "telegram",
    "binance", "coinbase", "sbi", "hdfc", "icici", "axis", "paytm", "phonepe", "gpay",
    "amazon", "flipkart", "netflix", "paypal", "microsoft", "elon", "tesla", "spacex",
    "mrbeast", "crypto", "forex", "airdrop", "giveaway", "winner"
  ];

  const impersonatorSuffixes = [
    "_official", "_support", "_help", "_customercare", "_care", "_24x7", "_desk",
    "_backup", "_temp", "_fanpage", "_real", "_original", "_team", "_mod", "_admin",
    "_winner", "_claim", "_airdrop", "_bonus", "_refund", "_dept", "_officia1", "_supp0rt"
  ];

  const hasImpersonatorHandle = impersonatorSuffixes.some((s) => target.toLowerCase().includes(s));
  const hasBrandKeyword = brandKeywords.some((b) => target.toLowerCase().includes(b));

  if (
    (hasImpersonatorHandle && hasBrandKeyword) ||
    combined.includes("customer care") ||
    combined.includes("toll free") ||
    combined.includes("24x7 helpline") ||
    combined.includes("refund support")
  ) {
    deduction += 65;
    flags.push("High-Risk Impersonation Handle / Fake Support Desk");
    flags.push("Unverified Customer Care / Helpline Pattern");
    category = "Customer Support Impersonation";
  }

  if (
    combined.includes("crypto") ||
    combined.includes("forex") ||
    combined.includes("binary option") ||
    combined.includes("mining pool") ||
    combined.includes("guaranteed profit") ||
    combined.includes("earn $") ||
    combined.includes("earn ₹") ||
    combined.includes("passive income") ||
    combined.includes("investment plan") ||
    combined.includes("fx_") ||
    combined.includes("trader_") ||
    combined.includes("signals") ||
    combined.includes("airdrop")
  ) {
    deduction += 60;
    flags.push("Crypto / Forex Investment Solicitation");
    flags.push("Unregulated Financial Trading Lure");
    category = "Crypto & Financial Scam";
  }

  if (
    combined.includes("giveaway") ||
    combined.includes("congratulations you won") ||
    combined.includes("winner claim") ||
    combined.includes("lucky draw") ||
    combined.includes("free iphone") ||
    combined.includes("dm to claim") ||
    combined.includes("send screenshot to claim")
  ) {
    deduction += 60;
    flags.push("Advance-Fee Prize / Giveaway Trap");
    flags.push("Unsolicited Winner Notification Pattern");
    category = "Giveaway Scam";
  }

  if (
    (combined.includes("army") || combined.includes("military") || combined.includes("peacekeeping") || combined.includes("syria") || combined.includes("surgeon") || combined.includes("widower") || combined.includes("widowed")) &&
    (combined.includes("honest") || combined.includes("soulmate") || combined.includes("whatsapp") || combined.includes("looking for love") || combined.includes("deploy"))
  ) {
    deduction += 65;
    flags.push("Romance / Military Catfishing Persona Signature");
    flags.push("Off-Platform Redirection Trap");
    category = "Romance Catfish Scam";
  }

  const digitMatches = target.match(/\d+/g);
  const totalDigits = digitMatches ? digitMatches.join("").length : 0;
  if (totalDigits >= 5 || target.toLowerCase().includes("bot_") || target.toLowerCase().startsWith("user_")) {
    deduction += 35;
    flags.push("Synthetic Bot Handle Format / Numeric Swarm Identifier");
  }

  if (
    combined.includes("t.me/") ||
    combined.includes("telegram.me") ||
    combined.includes("wa.me/") ||
    combined.includes("bit.ly") ||
    combined.includes(".xyz") ||
    combined.includes(".top")
  ) {
    deduction += 40;
    flags.push("External Unverified Redirection Link (Telegram/WhatsApp/Link Shortener)");
  }

  let finalAuthenticity = Math.max(94 - deduction, 8);
  let verdict: "Genuine" | "Suspicious" | "Fake Profile Detected" = "Genuine";

  if (finalAuthenticity <= 40) {
    verdict = "Fake Profile Detected";
  } else if (finalAuthenticity <= 70) {
    verdict = "Suspicious";
  } else {
    flags.push("Organic handle structure", "No automated bot traits detected", "Consistent public metadata");
  }

  return res.json({
    authenticityScore: finalAuthenticity,
    verdict,
    confidence: verdict === "Fake Profile Detected" ? 94 : verdict === "Suspicious" ? 85 : 92,
    riskIndicators: flags,
    explanation:
      verdict === "Fake Profile Detected"
        ? `High-risk indicators identified on ${target}. The profile matches known patterns of ${category}, including deceptive handle syntax and external redirection.`
        : verdict === "Suspicious"
        ? `Potential irregularities detected on ${target}. Unverified linking patterns or automated traits present. Exercise caution.`
        : `The profile ${target} displays organic behavioral attributes, healthy identity metadata, and zero detected scam triggers.`,
    recommendations:
      verdict === "Fake Profile Detected"
        ? [
            "Do NOT click any bio links, payment links, or external chat invitations (Telegram/WhatsApp).",
            "Never send money, OTPs, gift cards, or cryptocurrency to this account.",
            "Report the profile immediately to the platform moderation team and block the user.",
            "If this account claims to be a brand or bank, verify through their official website or verified toll-free number.",
          ]
        : verdict === "Suspicious"
        ? [
            "Request video verification or contact through an alternate verified platform before engaging.",
            "Avoid sharing personal identity, workplace, or financial information.",
            "Examine follower comments and engagement history to verify authenticity.",
          ]
        : [
            "Standard online privacy and security practices apply.",
            "Always verify identity before engaging in peer-to-peer financial transactions.",
          ],
  });
});

// 3. AI Cyber Assistant ("NOVA AI") Chat Endpoint
app.post("/api/assistant/chat", async (req, res) => {
  const { messages = [], language = "English" } = req.body;
  const lastUserMsg = messages[messages.length - 1]?.content || "Hello";

  const ai = getAI();
  if (ai) {
    try {
      const systemInstruction = `You are NOVA AI, the world-class intelligent cyber defense companion inside the SYRA NOVA cybersecurity ecosystem.
You are professional, reassuring, crystal-clear, highly knowledgeable in:
- Scam & fraud prevention (SMS, WhatsApp, Email, UPI, Bank Phishing, Lottery scams)
- Digital Identity Guardian (password health, data breach recovery, privacy footprint)
- Deepfake and voice clone detection advice
- Browser Shield and real-time safe browsing
- Step-by-step incident recovery (hacked Instagram/Google, unauthorized UPI transactions, SIM swap)
- National Cyber Helpline guidance (such as India's 1930 / cybercrime.gov.in and international CERTs)

Language requested: ${language}.
Keep responses structured, concise, visually organized with bullet points, actionable steps, and zero technical jargon unless asked.
Never generate fake links. Provide real, sound cybersecurity best practices.`;

      const response = await ai.models.generateContent({
        model: "gemini-3.7-flash",
        contents: lastUserMsg,
        config: {
          systemInstruction,
        },
      });

      return res.json({
        reply: response.text,
        language,
        timestamp: new Date().toISOString(),
      });
    } catch (err) {
      console.error("Gemini API assistant error:", err);
    }
  }

  // Fallback intelligent responses
  const lower = lastUserMsg.toLowerCase();
  let reply = `Hello! I am **NOVA AI**, your SYRA NOVA cyber guardian.\n\nHere are some actions I can assist you with right now:\n- 🛡️ **Analyze a suspicious message or email**\n- 🔍 **Check a social profile or website link**\n- 🚨 **Guide you through account recovery (Instagram, Google, UPI)**\n- 🔐 **Assess your password strength and privacy settings**\n\nHow can I protect you today?`;

  if (lower.includes("upi") || lower.includes("bank") || lower.includes("money") || lower.includes("fraud") || lower.includes("lost money")) {
    reply = `🚨 **Emergency Cyber Fraud Recovery Steps:**\n\n1. **Call Cyber Crime Helpline 1930** immediately (Golden Hour response stops illicit fund transfers).\n2. **Block Bank Account & UPI**: Open your banking app or call their fraud helpline to freeze digital banking access.\n3. **Preserve Evidence**: Take screenshots of transaction IDs, sender SMS, payment receipt, and chat messages.\n4. **Register Complaint**: File an official report at **cybercrime.gov.in** with the transaction reference.\n\nSYRA NOVA's **Emergency SOS** module can automatically compile your evidence dossier into a formal PDF report.`;
  } else if (lower.includes("hacked") || lower.includes("instagram") || lower.includes("facebook") || lower.includes("google")) {
    reply = `🔒 **Account Recovery Protocol:**\n\n1. **Secure Associated Email**: Change your email password first and terminate active sessions.\n2. **Official Account Recovery**: Use the platform's official recovery flow (e.g. instagram.com/hacked or accounts.google.com/signin/recovery).\n3. **Revoke Third-Party App Access**: Check connected apps and remove unfamiliar integrations.\n4. **Enable Multi-Factor Authentication (MFA)** using an Authenticator app, not SMS if possible.\n5. **Alert Contacts**: Notify friends that your account was compromised so they do not click malicious links sent in your name.`;
  } else if (lower.includes("deepfake") || lower.includes("voice")) {
    reply = `🤖 **Deepfake & Voice Clone Defense:**\n\n- **Live Verification Code**: Establish a secret "family safe word" to verify unexpected emergency phone calls.\n- **Visual Artifacts**: Look for unnatural eye blinks, edge distortion around lips and teeth, and lighting inconsistencies.\n- **Audio Anomaly**: Cloned voices often lack natural breathing pauses, subtle background room acoustic reflections, or micro-intonations.\n- Use the **SYRA NOVA Deepfake Detection** tool to scan audio and video files.`;
  }

  return res.json({
    reply,
    language,
    timestamp: new Date().toISOString(),
  });
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`SYRA NOVA server running on http://0.0.0.0:${PORT}`);
  });
}

if (!process.env.VERCEL) {
  startServer();
}

export default app;
